config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

  resources :posts do
    resources :comments
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

 private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

#AUTHENTICATE
    http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

	def new
		@post = Post.new
	end

	  def create
    @post = Post.new(post_params)
 
    if @post.save
    	redirect_to @post
	else
		render 'new'
	end
  end

	def show
		@post = Post.find(params[:id])
    end

    def index
    	@posts = Post.all
    end

    def edit
    	@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post
			else
				render "edit"
			end
		end

		def destroy
			@post = Post.find(params[:id])
			@post.destroy

			redirect_to posts_path
			
		end
		

	private
	def post_params
		params.require(:post).permit(:title, :text)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p class='comment'>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>	

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<center><h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

</center>

app/views/posts/index.html.erb
<center>
<div class="menu">
			<ul class="ulka">
				<li class="current_page_item"><a class="ashka_current_page" href="#">Homepage</a></li>
				<li class="lishka"><a class="ashka" href="#">Blog</a></li>
				<li class="lishka"><a class="ashka" href="#">Photos</a></li>
				<li class="lishka"><a class="ashka" href="#">About</a></li>
				<li class="lishka"><a class="ashka" href="#">Contact</a></li>
			</ul>
		</div>


  <% @posts.each do |post| %>


<div class="posts">
	<h2 class="title"><%= post.title %> </h2>
	<div class="accordion"id="accordion2">

<div class="accordion-heading">

</div>
<div id="collapse<%=post.id%>" class="accordion-body collapse">
<div class="accordion-inner">
	  <h6 class="text"> <%= post.text %> </h6>

	  </div>
</div>
</div>
 <p><%=truncate(post.text,:length=>200)%> </p>
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%=post.id%>">
Показать полностью
</a>

  </div>
<div class="post_buttons">
    <tr><%= link_to 'Show', post, :class=>"btn btn-info",:type=>"button" %></tr>
    <tr><%= link_to 'Edit', edit_post_path(post), :class=>"btn btn-warning", :type=>"button" %></tr>
    <tr><%= link_to 'Delete', post_path(post), :class=>"btn btn-danger", :type=>"button", method: :delete, data: {confirm: 'Are you sure?'} %></tr>  
</div>
<% end %>
</center>

app/views/posts/new.html.erb
<center><h1>New post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>
</center>

app/views/posts/show.html.erb
<body>
<center>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
 
<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>
</center>
</body>

app/views/welcome/index.html.erb
<h1 class="kolya_zaebal">Hello, Rails!</h1>
<%= link_to "Мой Блог", posts_path,:class=>"etot_zasranec_nichego_ne_chitaet" %>